# Generated by Django 5.0.4 on 2025-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка на платеж'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, null=True, verbose_name='id-платежа'),
        ),
    ]
